[package]
name = "twfeedrs"
version = "0.1.0"
edition = "2024"

[dependencies]
fastrace = "0.7.9"
kanal = "0.1.1"
nom = "8.0.0"
compact_str = "0.9.0"
monoio = "0.2.4"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4", features = ["derive"] }
bytes = "1.10.1"

